visual_context_recognition_task:
  description: >
    Give a detailed description of image path: {image}
    Analyse the image and provide insights on visual emotional content.
    If there is no image_path: {image}, provided, note that in the report, else follow the next steps:
    1. Start by clearly identifying the situation or issue the user wants to work on if given.
    2. Questioning the validity of negative thoughts. Are there alternative, more balanced, or rational thoughts that might be more helpful in the situation?
    3. Reframe the user's unhelpful thoughts and situations into more balanced, realistic, and constructive ones.
    Return a report of your analysis.
  expected_output: >
    A structured report:
    First section should contain a detailed description of the image. Second section contains the analysis of the image which covers the insights into the user, the situation of the user,
    the emotional content of the image and the emotional tone of the image. The third section provides suggestions to possible reframing techniques if they are needed.
  agent: imageTherapist

cognitive_reframing_task:
  description: >
    If text: {text} is empty do nothing and note that in the feedback document.
    Analyse {text}, to identify cognitive distortions.
    If negative thoughts are identified do the following steps:
    1. Start by clearly identifying the situation or issue the user wants to work on if given.
    2. Apply emotion detection on the given text
    3. If the text is positive give only as suggestion to pursue with usual smalltalk with the user instead of reframing techniques
    4. Questioning the validity of negative thoughts. Are there alternative, more balanced, or rational thoughts that might be more helpful in the situation?
    5. Reframe the user's unhelpful thoughts and situations into more balanced, realistic, and constructive ones.
    Create a deatailed feedback document
  expected_output: >
    A structured feedback document:
    The first section contains {text}. The second section contains the analysis which covers identified cognitive distortions, the emotional state and the emotional tone of the user.
    The third section contains possible suggestions to continue the conversation or if there are negative thoughts on how to reframe them.
  agent: textTherapist

conversation_task:
  description: >
    Introduce yourself if the user introduces himself/herself.
    Have an engaging back-and-forth conversation with the user.
    Engage in small talk to get to know the user.
    Aggregate outputs from multiple agents if they are provided.
    Analyse all insights to form a holistic view of the user's mental and emotional state.
    Synthesize tailored feedback that incorporates elements from all specialists.
    If there are any negative thoughts, ask the user about the reasons or the cause of the problem with the user.
    Only apply the provided suggestions of the specialists if they are needed.
  expected_output: >
    Provide an answer to the input of the user. The answer should be between 1 or 2 sentences.
  agent: therapist
