version: "3.8"

services:
  therapist:
    build:
      context: ./therapist
      dockerfile: Dockerfile
    image: therapist:latest
    container_name: therapist
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Add timeout configurations
      - CREWAI_TIMEOUT=120
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      # Optimize PyTorch for CPU if no GPU
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - media:/media/uploads
      # Cache models to avoid re-downloading
      - model_cache:/root/.cache
    # Resource limits and reservations
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "2"
          memory: 4G
    # Increase shared memory for PyTorch
    shm_size: "2gb"

  therapistdb:
    build:
      context: ./therapistdb
      dockerfile: Dockerfile
    image: therapistdb:latest
    container_name: therapistdb
    env_file:
      - .env
    depends_on:
      - db
    restart: "on-failure"

  db:
    image: postgres:17.2-alpine
    container_name: chat_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  db_data:
  media:
  model_cache:
