image_analysis_task:
  description: |
    Use the vision tool only once per image
    Do not retry the same image multiple times.
    1. **Describe what you see**  
       – Mention objects, people, colours, composition, and any obvious symbols.  
       – Point out patterns or anything that looks intentional.
    2. **Read the emotional tone**  
       – What feelings are conveyed (e.g., calm, tension, joy, ambiguity)?  
       – Cite the specific visual cues that led to those feelings.
    3. **Link to the user’s situation** (only if a situation was provided).  
       – Show how the emotions in the image might mirror or magnify the user’s state.
    4. **Offer helpful re-frames**  
       – Question any negative interpretations you inferred.  
       – Suggest alternative, balanced viewpoints or silver linings.  
       – Use gratitude or light humour **only if it feels natural**.
    5. **Invite reflection**  
       – End with one open question to help the user look at the image (and their feelings) from a fresh angle.
  expected_output: |
    1. Objective description of the image.  
    2. Emotional analysis (with links to user context if given).  
    3. Reframing suggestions and one reflective question for the therapist to build on.
  agent: imageTherapist

text_analysis_task:
  description: |
    1. **Spot emotions & cognitive distortions**  
       – Label the dominant feelings and name any distortions (e.g., catastrophising, mind-reading).
    2. **If emotions are neutral or positive**  
       – Suggest continuing light conversation; do **not** force reframing.
    3. **If emotions are negative**  
       – a. Identify the triggering situation.  
       – b. Challenge the negative thought: provide 1-2 balanced counter-points.  
       – c. Perspective shift: How might a close friend view this?  
       – d. Reframe: craft 1–2 constructive alternative thoughts.  
       – e. De-catastrophise: note realistic impact & coping ideas.  
       – f. Optionally add gratitude or gentle humour.
    4. **Prompt reflection**  
       – End with a question that invites the user to react to the new framing.
  expected_output: |
    1. Original text ({text}).  
    2. Analysis: emotions, distortions, overall tone.  
    3. Reframed thoughts + 1 follow-up question for the therapist.
  agent: textTherapist

voice_analysis_task:
  description: |
    Use each tool only once per audio file.
    Do not retry the same audio multiple times.
    1. Transcribe the audio (VoiceTranscriptionTool) and fix obvious errors.  
    2. Detect emotional tone (SERTool).  
    3. Analyse the transcript for emotions & distortions; identify any described situation.
    4. **If tone is negative**  
       – a. Gently challenge the unhelpful thought with 1-2 balanced views.  
       – b. Offer an outside perspective.  
       – c. Reframe into a constructive interpretation (growth focus).  
       – d. De-catastrophise: realistic outcomes + coping ideas.  
       – e. Optional gratitude or humour.
    5. **End with a reflection prompt** encouraging the user to consider the reframed view.
  expected_output: |
    1. Transcription of the audio.  
    2. Emotional analysis (tone, distortions, possible issue).  
    3. Reframes + 1 reflection question for further discussion.
  agent: voiceTherapist

conversation_task:
  description: |
    1. READ the user's message. If it contains a question asking for steps, advice, or "how to" do something:
       - Answer their question with specific steps IMMEDIATELY
       - Do NOT start with validation or generic statements
       - Give them the practical information they asked for
       IMPORTANT: Don't repeat advices that you have given in the conversation history already

    2. ANALYZE the three reports (textTherapist, imageTherapist, voiceTherapist):
       - If user shared an image, you MUST reference what the image shows and how it reflects their emotional state
       - If user shared voice, reference tone, pace, or emotional indicators
       - Always integrate these insights naturally into your response
       - Also crossreference the insights of the different inputs and reports from the current input

    3. IF reports show negative patterns → add gentle cognitive reframing
       IF no negativity → respond supportively

    4. End with one follow-up question

    CRITICAL: Always reference any images, voice recordings, or other media the user shared. Connect these to their emotional experience.

    EXAMPLE:
    User asks: "Can you give me steps to talk to my family?" + shares image of sad figure

    RIGHT: "Here are steps to have this conversation: 1) Choose a private moment, 2) Start with 'I need to share something difficult', 3) Be direct about what happened, 4) Let them know what support you need. I can see from the image you shared - that figure under the dark cloud really captures how heavy and overwhelming this feels right now. How do you think your family might react when you share this news?"

  expected_output: |
    When user asks a direct question:
    - Start with concrete steps/advice (2-3 sentences)
    - Reference any images, voice, or other media they shared and connect it to their emotional state
    - Brief acknowledgment of difficulty (1 sentence) 
    - One specific follow-up question

    When no direct question:
    - Acknowledge what they shared
    - Always reference any images, voice recordings, or media shared
    - Integrate all multimodal insights (what you see in images, hear in voice, read in text)
    - Apply cognitive reframing if negativity detected
    - One follow-up question

    ALWAYS mention and interpret any visual or audio content the user provides.

  agent: therapist
